In [1]:
import sys
!{sys.executable} -m pip install geopy
!{sys.executable} -m pip install pandas

Requirement already satisfied: geopy in /opt/homebrew/anaconda3/lib/python3.11/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from geopy) (2.0)
Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.11/site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
#import pandas library
import pandas as pd
from geopy.geocoders import Nominatim

In [3]:
#read in csv file from directory
agmp_data = pd.read_csv("/Users/perceval/data_science/agmp/gwas_catalog_data_MAY2024.csv",low_memory=False)

In [4]:
import os
file_path = '/Users/perceval/data_science/agmp/gwas_catalog_data_MAY2024.csv'
file_size_bytes = os.path.getsize(file_path)

file_size_kb = file_size_bytes / 1024
print(f"The size of the file is: {file_size_kb:.2f} KB")

The size of the file is: 186585.54 KB

In [5]:

agmp_data

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,publication,publication_year,source,id_in_source,variant_type,drug_name,ID Drug bank,state,Indication,IUPAC_name
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90916,rs62235072,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,5.000000e-14,ANKRD54,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90917,chr17:44351387,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,NaN,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90918,rs17712208,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,4.000000e-13,PROX1-AS1,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90919,rs13016086,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,8.000000e-13,BABAM2,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90920,rs77629332,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,RHOA,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN

In [6]:

agmp_data_wip = agmp_data

In [7]:
agmp_data_wip

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,publication,publication_year,source,id_in_source,variant_type,drug_name,ID Drug bank,state,Indication,IUPAC_name
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90916,rs62235072,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,5.000000e-14,ANKRD54,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90917,chr17:44351387,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,NaN,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90918,rs17712208,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,4.000000e-13,PROX1-AS1,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90919,rs13016086,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,8.000000e-13,BABAM2,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90920,rs77629332,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,RHOA,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN

In [8]:
# # convert the csv file into a data frame
# df = pd.DataFrame(agmp_data)

In [9]:
# # display the contents of the dataframe
# df

In [10]:
agmp_data_wip

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,publication,publication_year,source,id_in_source,variant_type,drug_name,ID Drug bank,state,Indication,IUPAC_name
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,23903356,6/18/2015,GWAS Catalog,GCST002110,SNV,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90916,rs62235072,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,5.000000e-14,ANKRD54,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90917,chr17:44351387,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,NaN,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90918,rs17712208,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,4.000000e-13,PROX1-AS1,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90919,rs13016086,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,8.000000e-13,BABAM2,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN
90920,rs77629332,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,RHOA,NaN,...,33462484,NaN,GWAS Catalog,GCST90019517,SNV,NaN,NaN,NaN,NaN,NaN

In [11]:

# split the column "origin_of_participants" into columns separated by a ,
split_values = agmp_data_wip['origin_of_participants'].str.split(',', expand=True)

In [12]:
# display the split values
split_values

             0     1     2     3     4     5     6     7     8     9     10
0      Barbados  None  None  None  None  None  None  None  None  None  None
1      Barbados  None  None  None  None  None  None  None  None  None  None
2      Barbados  None  None  None  None  None  None  None  None  None  None
3      Barbados  None  None  None  None  None  None  None  None  None  None
4      Barbados  None  None  None  None  None  None  None  None  None  None
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
90916        NR  None  None  None  None  None  None  None  None  None  None
90917        NR  None  None  None  None  None  None  None  None  None  None
90918        NR  None  None  None  None  None  None  None  None  None  None
90919        NR  None  None  None  None  None  None  None  None  None  None
90920        NR  None  None  None  None  None  None  None  None  None  None

[90921 rows x 11 columns]

In [13]:

# rename the column names
split_values.columns = [f'country_participant_0{i+1}' for i in range(split_values.shape[1])]

In [14]:
split_values.columns

Index(['country_participant_01', 'country_participant_02',
       'country_participant_03', 'country_participant_04',
       'country_participant_05', 'country_participant_06',
       'country_participant_07', 'country_participant_08',
       'country_participant_09', 'country_participant_010',
       'country_participant_011'],
      dtype='object')

In [15]:

# Concatenate the split with the original data frame
result_df = pd.concat([agmp_data_wip, split_values], axis=1)

In [16]:
result_df.head()

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,country_participant_02,country_participant_03,country_participant_04,country_participant_05,country_participant_06,country_participant_07,country_participant_08,country_participant_09,country_participant_010,country_participant_011
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,None,None,None,None,None,None,None,None,None,None
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,None,None,None,None,None,None,None,None,None,None
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,None,None,None,None,None,None,None,None,None,None
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,None,None,None,None,None,None,None,None,None,None
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,None,None,None,None,None,None,None,None,None,None

In [17]:
result_df.columns

Index(['id', 'Pubmed_id', 'phenotype', 'origin_of_participants',
       'geographical_region', 'Ethnicity', 'mixed_population', 'p-value',
       'curated_gene_symbol', 'Notes', 'study_type', 'gene_symbol_mined',
       'gene_name', 'chromosome', 'uniprot', 'function', 'data_ac',
       'publication_type', 'title', 'publication', 'publication_year',
       'source', 'id_in_source', 'variant_type', 'drug_name', 'ID Drug bank',
       'state', 'Indication', 'IUPAC_name', 'country_participant_01',
       'country_participant_02', 'country_participant_03',
       'country_participant_04', 'country_participant_05',
       'country_participant_06', 'country_participant_07',
       'country_participant_08', 'country_participant_09',
       'country_participant_010', 'country_participant_011'],
      dtype='object')

In [18]:

result_df['latitude_01'] = ''
result_df['longitude_01'] = ''
result_df['latitude_02'] = ''
result_df['longitude_02'] = ''
result_df['latitude_03'] = ''
result_df['longitude_03'] = ''
result_df['latitude_04'] = ''
result_df['longitude_04'] = ''
result_df['latitude_05'] = ''
result_df['longitude_05'] = ''
result_df['latitude_06'] = ''
result_df['longitude_06'] = ''
result_df['latitude_07'] = ''
result_df['longitude_07'] = ''
result_df['latitude_08'] = ''
result_df['longitude_08'] = ''
result_df['latitude_09'] = ''
result_df['longitude_09'] = ''
result_df['latitude_10'] = ''
result_df['longitude_10'] = ''
result_df['latitude_11'] = ''
result_df['longitude_11'] = ''

In [19]:
result_df.columns

Index(['id', 'Pubmed_id', 'phenotype', 'origin_of_participants',
       'geographical_region', 'Ethnicity', 'mixed_population', 'p-value',
       'curated_gene_symbol', 'Notes', 'study_type', 'gene_symbol_mined',
       'gene_name', 'chromosome', 'uniprot', 'function', 'data_ac',
       'publication_type', 'title', 'publication', 'publication_year',
       'source', 'id_in_source', 'variant_type', 'drug_name', 'ID Drug bank',
       'state', 'Indication', 'IUPAC_name', 'country_participant_01',
       'country_participant_02', 'country_participant_03',
       'country_participant_04', 'country_participant_05',
       'country_participant_06', 'country_participant_07',
       'country_participant_08', 'country_participant_09',
       'country_participant_010', 'country_participant_011', 'latitude_01',
       'longitude_01', 'latitude_02', 'longitude_02', 'latitude_03',
       'longitude_03', 'latitude_04', 'longitude_04', 'latitude_05',
       'longitude_05', 'latitude_06', 'longitude_06', 'latitude_07',
       'longitude_07', 'latitude_08', 'longitude_08', 'latitude_09',
       'longitude_09', 'latitude_10', 'longitude_10', 'latitude_11',
       'longitude_11'],
      dtype='object')

In [20]:
agmp_data_wip = result_df.iloc[:200000]

In [21]:
agmp_data_wip.shape
agmp_data_wip

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,latitude_07,longitude_07,latitude_08,longitude_08,latitude_09,longitude_09,latitude_10,longitude_10,latitude_11,longitude_11
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,,,,,,,,,,
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,,,,,,,,,,
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,,,,,,,,,,
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,,,,,,,,,,
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90916,rs62235072,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,5.000000e-14,ANKRD54,NaN,...,,,,,,,,,,
90917,chr17:44351387,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,NaN,NaN,...,,,,,,,,,,
90918,rs17712208,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,4.000000e-13,PROX1-AS1,NaN,...,,,,,,,,,,
90919,rs13016086,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,8.000000e-13,BABAM2,NaN,...,,,,,,,,,,
90920,rs77629332,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,RHOA,NaN,...,,,,,,,,,,

In [22]:
agmp_data_wip

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,latitude_07,longitude_07,latitude_08,longitude_08,latitude_09,longitude_09,latitude_10,longitude_10,latitude_11,longitude_11
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,,,,,,,,,,
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,,,,,,,,,,
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,,,,,,,,,,
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,,,,,,,,,,
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90916,rs62235072,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,5.000000e-14,ANKRD54,NaN,...,,,,,,,,,,
90917,chr17:44351387,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,NaN,NaN,...,,,,,,,,,,
90918,rs17712208,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,4.000000e-13,PROX1-AS1,NaN,...,,,,,,,,,,
90919,rs13016086,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,8.000000e-13,BABAM2,NaN,...,,,,,,,,,,
90920,rs77629332,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,RHOA,NaN,...,,,,,,,,,,

In [23]:
#improve to make results retrieved faster
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp01")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_01'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_01'] = agmp_data_wip['country_participant_01'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_01'] = agmp_data_wip['country_participant_01'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_01', 'longitude_01']] = agmp_data_wip[['latitude_01', 'longitude_01']].fillna("")

In [24]:

agmp_data_wip.loc[:,["latitude_01","longitude_01"]]

       latitude_01  longitude_01
0        13.150033    -59.525030
1        13.150033    -59.525030
2        13.150033    -59.525030
3        13.150033    -59.525030
4        13.150033    -59.525030
...            ...           ...
90916    -0.525231    166.932443
90917    -0.525231    166.932443
90918    -0.525231    166.932443
90919    -0.525231    166.932443
90920    -0.525231    166.932443

[90921 rows x 2 columns]

In [25]:
#improve to make results retrieved faster 02
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp02")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_02'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_02'] = agmp_data_wip['country_participant_02'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_02'] = agmp_data_wip['country_participant_02'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_02', 'longitude_02']] = agmp_data_wip[['latitude_02', 'longitude_02']].fillna("")

In [26]:
agmp_data_wip.loc[:,["latitude_02","longitude_02"]]

       latitude_02  longitude_02
0        44.933143      7.540121
1        44.933143      7.540121
2        44.933143      7.540121
3        44.933143      7.540121
4        44.933143      7.540121
...            ...           ...
90916    44.933143      7.540121
90917    44.933143      7.540121
90918    44.933143      7.540121
90919    44.933143      7.540121
90920    44.933143      7.540121

[90921 rows x 2 columns]

In [27]:
#improve to make results retrieved faster 03
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp03")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_03'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_03'] = agmp_data_wip['country_participant_03'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_03'] = agmp_data_wip['country_participant_03'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_03', 'longitude_03']] = agmp_data_wip[['latitude_03', 'longitude_03']].fillna("")

In [28]:
agmp_data_wip.loc[:,["latitude_03","longitude_03"]]

       latitude_03  longitude_03
0        44.933143      7.540121
1        44.933143      7.540121
2        44.933143      7.540121
3        44.933143      7.540121
4        44.933143      7.540121
...            ...           ...
90916    44.933143      7.540121
90917    44.933143      7.540121
90918    44.933143      7.540121
90919    44.933143      7.540121
90920    44.933143      7.540121

[90921 rows x 2 columns]

In [29]:
#improve to make results retrieved faster 04
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp04")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_04'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_04'] = agmp_data_wip['country_participant_04'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_04'] = agmp_data_wip['country_participant_04'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_04', 'longitude_04']] = agmp_data_wip[['latitude_04', 'longitude_04']].fillna("")

In [30]:
agmp_data_wip.loc[:,["latitude_04","longitude_04"]]

       latitude_04  longitude_04
0        44.933143      7.540121
1        44.933143      7.540121
2        44.933143      7.540121
3        44.933143      7.540121
4        44.933143      7.540121
...            ...           ...
90916    44.933143      7.540121
90917    44.933143      7.540121
90918    44.933143      7.540121
90919    44.933143      7.540121
90920    44.933143      7.540121

[90921 rows x 2 columns]

In [31]:
#improve to make results retrieved faster 05
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp05")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_05'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_05'] = agmp_data_wip['country_participant_05'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_05'] = agmp_data_wip['country_participant_05'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_05', 'longitude_05']] = agmp_data_wip[['latitude_05', 'longitude_05']].fillna("")

In [32]:
agmp_data_wip.loc[:,["latitude_05","longitude_05"]]

       latitude_05  longitude_05
0        44.933143      7.540121
1        44.933143      7.540121
2        44.933143      7.540121
3        44.933143      7.540121
4        44.933143      7.540121
...            ...           ...
90916    44.933143      7.540121
90917    44.933143      7.540121
90918    44.933143      7.540121
90919    44.933143      7.540121
90920    44.933143      7.540121

[90921 rows x 2 columns]

In [33]:
#improve to make results retrieved faster 06
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp06")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_06'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_06'] = agmp_data_wip['country_participant_06'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_06'] = agmp_data_wip['country_participant_06'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_06', 'longitude_06']] = agmp_data_wip[['latitude_06', 'longitude_06']].fillna("")

In [34]:
agmp_data_wip.loc[:,["latitude_06","longitude_06"]]

       latitude_06  longitude_06
0        44.933143      7.540121
1        44.933143      7.540121
2        44.933143      7.540121
3        44.933143      7.540121
4        44.933143      7.540121
...            ...           ...
90916    44.933143      7.540121
90917    44.933143      7.540121
90918    44.933143      7.540121
90919    44.933143      7.540121
90920    44.933143      7.540121

[90921 rows x 2 columns]

In [35]:
#improve to make results retrieved faster 07
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp07")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_07'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_07'] = agmp_data_wip['country_participant_07'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_07'] = agmp_data_wip['country_participant_07'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_07', 'longitude_07']] = agmp_data_wip[['latitude_07', 'longitude_07']].fillna("")

In [36]:

agmp_data_wip.loc[:,["latitude_07","longitude_07"]]

       latitude_07  longitude_07
0        44.933143      7.540121
1        44.933143      7.540121
2        44.933143      7.540121
3        44.933143      7.540121
4        44.933143      7.540121
...            ...           ...
90916    44.933143      7.540121
90917    44.933143      7.540121
90918    44.933143      7.540121
90919    44.933143      7.540121
90920    44.933143      7.540121

[90921 rows x 2 columns]

In [37]:
#improve to make results retrieved faster 08
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp08")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_08'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_08'] = agmp_data_wip['country_participant_08'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_08'] = agmp_data_wip['country_participant_08'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_08', 'longitude_08']] = agmp_data_wip[['latitude_08', 'longitude_08']].fillna("")

In [38]:
#improve to make results retrieved faster 09
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp09")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_09'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_09'] = agmp_data_wip['country_participant_09'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_09'] = agmp_data_wip['country_participant_09'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_09', 'longitude_09']] = agmp_data_wip[['latitude_09', 'longitude_09']].fillna("")

In [39]:
#improve to make results retrieved faster 10
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp10")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_010'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_10'] = agmp_data_wip['country_participant_010'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_10'] = agmp_data_wip['country_participant_010'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_10', 'longitude_10']] = agmp_data_wip[['latitude_10', 'longitude_10']].fillna("")

In [40]:
#improve to make results retrieved faster 11
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

# Initialize the geolocator with a user agent and rate limiter
geolocator = Nominatim(user_agent="myApp11")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # adjust delay to respect usage policy

# Assuming 'country_participant_01' contains the addresses
addresses = agmp_data_wip['country_participant_011'].unique()  # Process each unique address once

# Use a dictionary to cache geocoding results
location_cache = {}

# Pre-fetch locations for unique addresses
for address in addresses:
    if address not in location_cache:  # Check if address is already geocoded
        location = geocode(address)
        if location:
            location_cache[address] = (location.latitude, location.longitude)
        else:
            location_cache[address] = (None, None)

# Map the results back to the DataFrame without using a loop
agmp_data_wip['latitude_11'] = agmp_data_wip['country_participant_011'].map(lambda x: location_cache[x][0])
agmp_data_wip['longitude_11'] = agmp_data_wip['country_participant_011'].map(lambda x: location_cache[x][1])

# Handle missing data
agmp_data_wip[['latitude_11', 'longitude_11']] = agmp_data_wip[['latitude_11', 'longitude_11']].fillna("")

In [41]:
agmp_data_wip.columns

Index(['id', 'Pubmed_id', 'phenotype', 'origin_of_participants',
       'geographical_region', 'Ethnicity', 'mixed_population', 'p-value',
       'curated_gene_symbol', 'Notes', 'study_type', 'gene_symbol_mined',
       'gene_name', 'chromosome', 'uniprot', 'function', 'data_ac',
       'publication_type', 'title', 'publication', 'publication_year',
       'source', 'id_in_source', 'variant_type', 'drug_name', 'ID Drug bank',
       'state', 'Indication', 'IUPAC_name', 'country_participant_01',
       'country_participant_02', 'country_participant_03',
       'country_participant_04', 'country_participant_05',
       'country_participant_06', 'country_participant_07',
       'country_participant_08', 'country_participant_09',
       'country_participant_010', 'country_participant_011', 'latitude_01',
       'longitude_01', 'latitude_02', 'longitude_02', 'latitude_03',
       'longitude_03', 'latitude_04', 'longitude_04', 'latitude_05',
       'longitude_05', 'latitude_06', 'longitude_06', 'latitude_07',
       'longitude_07', 'latitude_08', 'longitude_08', 'latitude_09',
       'longitude_09', 'latitude_10', 'longitude_10', 'latitude_11',
       'longitude_11'],
      dtype='object')

In [42]:
agmp_data_wip.head()

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,latitude_07,longitude_07,latitude_08,longitude_08,latitude_09,longitude_09,latitude_10,longitude_10,latitude_11,longitude_11
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121

In [43]:
agmp_data_wip

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,latitude_07,longitude_07,latitude_08,longitude_08,latitude_09,longitude_09,latitude_10,longitude_10,latitude_11,longitude_11
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90916,rs62235072,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,5.000000e-14,ANKRD54,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90917,chr17:44351387,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,NaN,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90918,rs17712208,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,4.000000e-13,PROX1-AS1,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90919,rs13016086,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,8.000000e-13,BABAM2,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90920,rs77629332,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,RHOA,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121

In [44]:
agmp_data_final = agmp_data_wip

In [45]:
agmp_data_final

,id,Pubmed_id,phenotype,origin_of_participants,geographical_region,Ethnicity,mixed_population,p-value,curated_gene_symbol,Notes,...,latitude_07,longitude_07,latitude_08,longitude_08,latitude_09,longitude_09,latitude_10,longitude_10,latitude_11,longitude_11
0,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
1,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-13,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
2,rs1260326,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-11,GCKR,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
3,rs4746822,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,1.000000e-22,HKDC1,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
4,rs6517656,23903356,Glycemic traits (pregnancy),Barbados,African-American / Afro-Caribbean,NaN,False,6.000000e-16,BACE2,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90916,rs62235072,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,5.000000e-14,ANKRD54,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90917,chr17:44351387,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,NaN,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90918,rs17712208,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,4.000000e-13,PROX1-AS1,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90919,rs13016086,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,8.000000e-13,BABAM2,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121
90920,rs77629332,33462484,Serum albumin levels,NR,Africa unspecified,NaN,False,2.000000e-13,RHOA,NaN,...,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121,44.933143,7.540121

In [46]:
# name the output csv
csv_filename = 'second_import_job_run.csv'

In [47]:
#result of the csv file without the index column
agmp_data_final.to_csv(csv_filename, index=False)

In [48]:
print(f"DataFrame exported to /Users/perceval/data_science/agmp/{csv_filename}")

DataFrame exported to /Users/perceval/data_science/agmp/second_import_job_run.csv